### ISSUE TITLE
[Question] Change surface shot

### ISSUE THREAD

**Issue by BoxMannn** [iPortalTeam/PortalGun#20]
### According to your testing, does the issue occur with ONLY Portal Gun mod and Immersive Portals mod and Farbic API?

Yes

### Describe the issue

This isn't an issue but I don't know where else to ask this. Is there a way to change which blocks you can place portals on? I just wanted to know if there's a command or something.

**Comment by qouteall** [comment]
https://qouteall.fun/immptl/wiki/Portal-Gun.html#make-the-portal-gun-to-only-work-on-some-blocks
