### ISSUE TITLE
Getting artefacts when using the portal gun with sildur shader

### ISSUE THREAD

**Issue by Cape-City** [iPortalTeam/PortalGun#3]
### According to your testing, does the issue occur with ONLY Portal Gun mod and Immersive Portals mod and Farbic API?

Yes

### Describe the issue

The Portal itself works fine, no issues with my shader so far. When placing a portal with the gun it looks like this (TAA and motion blur are off):

![2023-04-22_20 24 02](https://user-images.githubusercontent.com/122229367/233800680-2fd7cb93-4aba-40a7-a685-9bf9645fcbdb.png)

![2023-04-22_20 24 07](https://user-images.githubusercontent.com/122229367/233800686-e2710fc2-d6c5-47ca-af6b-7cb3ffac8792.png)

I'm using MC 1.19.3 with fabric 0.14.19 and the latest version of both mods:

immersive-portals-2.5.4-mc1.19.3-fabric.jar
portalgun-5.0.0-mc1.19.3-fabric.jar

**Comment by ImSpaceLover** [comment]
Disable the motion blur, it doesn't work with Immersive Portals properly

**Comment by Cape-City** [comment]
Aus = Off - It's already disabled!

**Comment by ImSpaceLover** [comment]
Do these artifacts appear only when you're looking at a portal?

**Comment by Cape-City** [comment]
Yes, if i walk away and the portal gets out of sight, the artifacts are gone!
Without any shader, there are also no artifacts at all.

**Comment by ImSpaceLover** [comment]
Sorry, I don't think I know how to fix it then

**Comment by Cape-City** [comment]
The artifacts seems to be the light sources which the other portal sees.

**Comment by qouteall** [comment]
You are using a resourcepack so I don't know what thing is in the portal. A horse?

**Comment by ImSpaceLover** [comment]
> You are using a resourcepack so I don't know what thing is in the portal. A horse?

Looks like an Iron Golem to me

**Comment by Cape-City** [comment]
It's a golem ;) I'm using the PureBDcraft 128x Texturepack. I placed the portal once on a wall towards several torches and then the artifacts on the other side where exactly these torches.

**Comment by qouteall** [comment]
As I tested, ImmPtl with sildurs vibrant shader is kind of broken. It's recommended to use BSL shader for now.

**Comment by Cape-City** [comment]
It looks quite different with the BSL shader, but i think it will be normal after several days ;) The artifacts are now completly gone so far.
