### ISSUE TITLE
how to make portals spawn only on certain blocks

### ISSUE THREAD

**Issue by SonicFangame** [iPortalTeam/PortalGun#6]
### According to your testing, does the issue occur with ONLY Portal Gun mod and Immersive Portals mod and Farbic API?

Yes

### Describe the issue

how to make portals spawn only on certain blocks can you tell me all the controls please

**Comment by qouteall** [comment]
Do you mean nether portal? You can build an obsidian frame on the other side to control the position.

If there is no matching obsidian frame on the other side, it will generate a new frame. Currently does not support limiting the type of blocks that new frame can generate on.

**Comment by qouteall** [comment]
Said in the wiki https://qouteall.fun/immptl/wiki/Portal-Gun.html#make-the-portal-gun-to-only-work-on-some-blocks

This only works on the latest version of Portal Gun
